# Generated by Django 5.1.14 on 2026-04-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_product_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
